apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecs-app-deployment
  namespace: tsm
spec:
  selector:
    matchLabels:
      run: ecs-app
  replicas: 2
  template:
    metadata:
      labels:
        run: ecs-app
    spec:
      containers:
        - name: ecs-app-container
          image: gestanestle/event-command:3.0
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_HOSTNAME
              value: $(ECS_PG_CLUSTER_R_SERVICE_HOST)
---
apiVersion: v1
kind: Service
metadata:
  name: ecs-app-service
  labels:
    app: ecs-app
  namespace: tsm
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: ecs-app
