apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: postgres
    database.dbname: event_db
    database.port: 5432
    database.user: ${secrets:tsm/ecs-psql-user-secret:username}
    database.password: ${secrets:tsm/ecs-psql-user-secret:password}
    topic.prefix: event_db
    table.include.list: public.event
    time.precision.mode: connect 
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: false
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.add.fields: op, table
    #schema.history.internal.kafka.bootstrap.servers: kafka-cluster-kafka-bootstrap:9092
    #schema.history.internal.kafka.topic: schema-changes.inventory
