apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecs-postgres-volume
  labels:
    type: local
    app: ecs-postgres
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
