apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ecs-pg-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.6
  instances: 3
  superuserSecret:
    name: ecs-psql-superuser-secret

  bootstrap:
    initdb:
      database: event_db
      owner: eventmanager
      secret:
        name: ecs-psql-user-secret

  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
