apiVersion: v1
kind: ConfigMap
metadata:
  name: ecs-psql-config
  labels:
    app: ecs-postgres
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: event_db

---
apiVersion: v1
kind: Secret
metadata:
  name: ecs-psql-secret
data:
  POSTGRES_USER: eventmanager
  POSTGRES_PASSWORD: postgres
