apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecs-postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
